language: python

python:
  - 3.6
  - 3.7

before_install:
  - python -m pip install -U pip
  - python -m pip --version

install:
  - python -m pip install --upgrade codecov pytest-cov pytest
  - python -m pip install .

script:
  - travis_wait 30 python -m pytest --cov --cov-report term-missing

after_success:
  - codecov
